apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-deployment-scaler-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-deployment-scaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: k8s-deployment-scaler-clusterrole
  apiGroup: rbac.authorization.k8s.io
