apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-deployment-scaler.fullname" . }}
  labels:
    {{- include "k8s-deployment-scaler.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  {{- if .Values.replicaCount }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "k8s-deployment-scaler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-deployment-scaler.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "k8s-deployment-scaler.fullname" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
        readinessProbe:
          tcpSocket:
            port: 8443
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 12 }}