apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-deployment-scaler-role
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update"]
