apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-deployment-scaler-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-deployment-scaler.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: k8s-deployment-scaler-role
  apiGroup: rbac.authorization.k8s.io
