apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-deployment-scaler.fullname" . }}
  labels:
    {{- include "k8s-deployment-scaler.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "k8s-deployment-scaler.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443

